### ISSUE TITLE
Failing because the `branch` already exists

### ISSUE THREAD

**Issue by bnb** [gr2m/create-or-update-pull-request-action#245] opened 2020-10-29 15:56 UTC
Perhaps I'm just misunderstanding how the `branch` property in the config is supposed to work, but in using it after the initial run where it was created the Action is failing on every subsequent run with the assertion that `git checkout -b <branch>` already exists.

Here's an example run: 

https://github.com/bnb/node/runs/1327432876

Here's the error:

```
Remote branch "actions/authors-update" checked out locally.
Branch "actions/authors-update" does not yet exist on remote.
Error: Command failed with exit code 128 (Unknown system error -128): git checkout -b actions/authors-update
    at makeError (/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.x/dist/index.js:5673:11)
    at handlePromise (/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.x/dist/index.js:7624:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runShellCommand (/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.x/dist/index.js:707:32)
    at async checkOutRemoteBranch (/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.x/dist/index.js:699:5)
    at async main (/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.x/dist/index.js:567:32) {
  command: 'git checkout -b actions/authors-update',
  exitCode: 128,
  exitCodeName: 'Unknown system error -128',
  stdout: '',
  stderr: "fatal: A branch named 'actions/authors-update' already exists.",
  all: "fatal: A branch named 'actions/authors-update' already exists.",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined

```

**Comment by gr2m** [comment] 2020-10-29 18:03
I think this is the same problem as described in https://github.com/gr2m/create-or-update-pull-request-action/issues/177. I could really use help from a `git` expert to debug and fix this problem, it's really annoying :( Can you think of someone who might be able to help?

**Comment by bnb** [comment] 2020-10-29 19:17
perhaps @ethomson could help or knows someone who could? ❤️

**Comment by gr2m** [comment] 2020-10-29 19:39
pretty pleeeaaseee?

<img width="200" alt="image" src="https://user-images.githubusercontent.com/39992/97623989-af0bf880-19e3-11eb-9316-046c044b9680.png">

**Comment by ethomson** [comment] 2020-10-29 21:16
Well, here's what I'm seeing.  @bnb's run first [checks out the `actions/authors-update` branch locally](https://github.com/bnb/node/runs/1327432876#step:4:13).  In other words, the local branch `actions/authors-update` will be created to track `origin/actions/authors-update`.

But the stack trace says that it failed to _create_ a local `actions/authors-update` branch:

```
Error: Command failed with exit code 128 (Unknown system error -128): git checkout -b actions/authors-update
    at makeError (/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.x/dist/index.js:5673:11)
    at handlePromise (/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.x/dist/index.js:7624:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runShellCommand (/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.x/dist/index.js:707:32)
    at async checkOutRemoteBranch (/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.x/dist/index.js:699:5)
    at async main (/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.x/dist/index.js:567:32) {
```

This `checkout -b` is done in the [exception handler](https://github.com/gr2m/create-or-update-pull-request-action/blob/master/dist/index.js#L699).

So... something threw between the [checkout step](https://github.com/gr2m/create-or-update-pull-request-action/blob/master/dist/index.js#L690) (which [sent output indicating its success](https://github.com/bnb/node/runs/1327432876#step:4:13)) and [returning from the function](https://github.com/gr2m/create-or-update-pull-request-action/blob/master/dist/index.js#L696).

That means that [the `runShellCommand` that does the `cherry-pick` failed](https://github.com/gr2m/create-or-update-pull-request-action/blob/master/dist/index.js#L692).

If it were me, I would:
1. Not assume that an exception means that the remote branch doesn't exist.  Instead I'd look for `origin/{branch_name}`.  As we've seen, there are other failure modes.
2. Log some error messages about the `cherry-pick` failure.

I don't have a guess yet for why the `cherry-pick` would fail, but I do think that it's what's failing here.

**Comment by gr2m** [comment] 2020-10-29 22:09
Thanks Edward, I'll look into this tomorrow

**Comment by bnb** [comment] 2020-11-11 15:21
hey @gr2m! 👋🏻 

wanted to follow up to see if that was the right path?

**Comment by gr2m** [comment] 2020-11-11 18:26
sorry I didn't have a chance to look into it yet, but I have it on my todo list. I'll bump it to the top and keep you posted

**Comment by gr2m** [comment] 2020-11-12 23:49
I tried a few things to intentionally reproduce the problem but had no luck. If anyone could help me produce a test case I'd appreciate it. For now I'll add more error logging as suggested by @ethomson

**Comment by gr2m** [comment] 2020-11-13 00:01
Can you add a `ACTIONS_STEP_DEBUG` secret and set it to `true` as described here: https://github.com/gr2m/create-or-update-pull-request-action#debugging that will log the error from the `git cherry-pick` command to the build output

**Comment by gr2m** [comment] 2020-11-13 00:09
I think the solution is to simplify the git commands in the first place. What I want is to update an existing branch `update-branch`, with unstaged changes in the default branch `main`. Or if `update-branch` does not yet exist, create it.

I don't want to commit the changes to main, I want to commit them to `update-branch`. I experimented with stashing but that didn't work well so I ended up creating a temporary branch and then cherry-picking the changes from there.

What would the git commands be you would use in such a situation?

**Comment by ethomson** [comment] 2020-11-13 12:01
Ugh, this is one of those places where what you describe is relatively easy in the data modelling side (and I could whip you up some [libgit2](https://github.com/libgit2/libgit2) to do this quite easily) but I'm not 100% sure what the git commands are to get you there.

I think that using git itself, I'd let it do the work against an alternate index file (in other words, stage all those changes, but not against the _repository_ index, so the repo will still see them as unchanged), and create a commit from it and then set that to the head of `update-branch`.

I think that this will work:

```bash
TMPFILE=$(mktemp)

# add the files to the temporary staging area
GIT_INDEX_FILE="${TMPFILE}" git add .

# turn the temporary staging area into a tree object
TREE_ID=$(GIT_INDEX_FILE="${TMPFILE}" git write-tree)

# create a commit that points to that tree object
COMMIT_ID=$(git commit-tree -p HEAD -m 'commit message goes here' $TREE_ID)

# create or update the branch to the new commit
git branch -f 'branch_name_goes_here' $COMMIT_ID
```

**Comment by gr2m** [comment] 2020-11-13 19:30
Thanks @ethomson! Maybe we can make the current version work, but if not, I'll try the commands you suggested. Regarding `libgit2`, aren't there bindings for Node we could use? Would that help in this case?

Thanks @bnb, here is the full error we are facing

```
$ git cherry-pick --strategy recursive --strategy-option theirs tmp-create-or-update-pull-request-action-ow2fj5il2e
Error: Command failed with exit code 1 (EPERM): git cherry-pick --strategy recursive --strategy-option theirs tmp-create-or-update-pull-request-action-ow2fj5il2e
    at makeError (/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.x/dist/index.js:5673:11)
    at handlePromise (/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.x/dist/index.js:7624:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runShellCommand (/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.x/dist/index.js:707:32)
    at async checkOutRemoteBranch (/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.x/dist/index.js:692:5)
    at async main (/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.x/dist/index.js:567:32) {
  command: 'git cherry-pick --strategy recursive --strategy-option theirs tmp-create-or-update-pull-request-action-ow2fj5il2e',
  exitCode: 1,
  exitCodeName: 'EPERM',
  stdout: 'On branch actions/authors-update\n' +
    'You are currently cherry-picking commit c8d45a65ec.\n' +
    '  (all conflicts fixed: run "git cherry-pick --continue")\n' +
    '  (use "git cherry-pick --skip" to skip this patch)\n' +
    '  (use "git cherry-pick --abort" to cancel the cherry-pick operation)\n' +
    '\n' +
    'nothing to commit, working tree clean',
  stderr: 'The previous cherry-pick is now empty, possibly due to conflict resolution.\n' +
    'If you wish to commit it anyway, use:\n' +
    '\n' +
    '    git commit --allow-empty\n' +
    '\n' +
    "Otherwise, please use 'git cherry-pick --skip'",
  all: 'The previous cherry-pick is now empty, possibly due to conflict resolution.\n' +
    'If you wish to commit it anyway, use:\n' +
    '\n' +
    '    git commit --allow-empty\n' +
    '\n' +
    "Otherwise, please use 'git cherry-pick --skip'\n" +
    'On branch actions/authors-update\n' +
    'You are currently cherry-picking commit c8d45a65ec.\n' +
    '  (all conflicts fixed: run "git cherry-pick --continue")\n' +
    '  (use "git cherry-pick --skip" to skip this patch)\n' +
    '  (use "git cherry-pick --abort" to cancel the cherry-pick operation)\n' +
    '\n' +
    'nothing to commit, working tree clean',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined
}
```

It sounds like the problem is 

> nothing to commit, working tree clean

Sounds like this could be fixed by adding `--allow-empty` to the command? 🙏🏼  Let me try that 

so the action was triggered, no change occurred, and that's why the cherry pick failed somehow? I wish I could reproduce the state with pure git commands for easier debugging, I didn't manage to yet.

**Comment by gr2m** [comment] 2020-11-13 19:46
> Sounds like this could be fixed by adding `--allow-empty` to the command?

That did not seem to have worked 🤷🏼 
https://github.com/octokit/graphql-schema/runs/1397579382?check_suite_focus=true#step:7:326

But running `git cherry-pick --skip` in case of a "The previous cherry-pick is now empty" error did, at least in this case. Let me ship that and then see if that resolves the problem for you, too, @bnb?

**Closed** 2020-11-13 19:57 UTC

**Comment by bnb** [comment] 2020-11-16 15:16
@gr2m it worked 👍🏻 

https://github.com/bnb/node/actions/runs/366247539

**Comment by gr2m** [comment] 2020-11-16 16:38
yay! Thank you all for your help!
